set CMAKE_GENERATOR=
set CMAKE_GENERATOR_PLATFORM=
set CMAKE_GENERATOR_TOOLSET=

cmake -G "Ninja" %CMAKE_ARGS% -DCMAKE_C_COMPILER=%CC% -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -S . -B build

cmake --build build --parallel %CPU_COUNT%
cmake --install build
