{% set name = "libcint" %}
{% set version = "5.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sunqm/libcint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c111d82140e2e8415775e73f571a16456c9deadd36d58795edd170035b06f8a5
  patches:
    - 0001-Fix-test-location.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make

test:
  commands:
    - cd testsuite
    - python test_cint.py --quick
    - python test_3c2e.py --quick
  requires:
    - numpy
    - python
  source_files:
    - testsuite

about:
  home: https://github.com/sunqm/libcint
  summary: general GTO integrals for quantum chemistry
  dev_url: https://github.com/sunqm/libcint
  doc_url: http://wiki.sunqm.net/libcint
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
