{% set name = "libcint" %}
{% set version = "5.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sunqm/qcint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 25dd69fb6582ac73c4444f2b915cc8ee0f2bbe225e63b4f0f2af62d3d90b0bf2
  patches:
    - 0001-custom-march.patch

build:
  number: 0
  string: qcint
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make


about:
  home: https://github.com/sunqm/qcint
  summary: general GTO integrals for quantum chemistry
  dev_url: https://github.com/sunqm/qcint
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
    - chillenb